name: test & release

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: python -m unittest recent_projects_test
  release:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v2
    - name: Build artifacts
      run: make
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: '*.alfredworkflow'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
